# Pandas

1. `!` - The exclamation mark tells Jupyter to execute this as a shell command rather than Python code

2. `pip install pandas` - This is the actual shell command that uses pip (Python's package installer) to install the pandas library, which is a popular data manipulation and analysis library for Python

The command will download and install the pandas package and its dependencies into the current Python environment.

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: pandas in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

1. `import pandas as pd` - This statement imports the pandas library, which is a powerful data manipulation and analysis library for Python.

2. `as pd` - This creates an alias `pd` for the pandas library, allowing you to use `pd` instead of typing out `pandas` when calling pandas functions and methods throughout your code.

In [2]:
import pandas as pd

## Pandas Series Example

| Index | Value |
|------|------|
| a | 10 |
| b | 20 |
| c | 20 |
| d | 30 |
| e | 40 |
##### `pd.Series()`: Used to create a Pandas Series.
```python
pd.Series(data, index=index_labels)
```

In [3]:
s=pd.Series([10,20,20,30,40],index=['a','b','c','d','e'])
print(s)

a    10
b    20
c    20
d    30
e    40
dtype: int64

##### `s.values`: Used to get all values of the Series.

In [4]:
print("Values: ", s.values)

Values:  [10 20 20 30 40]

##### `s.index`: Used to get index labels of the Series.

In [5]:
print("Index ",s.index)

Index  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

##### `s.dtype`: Used to get the data type of Series elements.

In [6]:
print("Data Type ",s.dtype)

Data Type  int64

##### `head()`: Used to display the first 5 values of the Series.

In [7]:
s.head()

a    10
b    20
c    20
d    30
e    40
dtype: int64

##### `tail()`: Used to display the last 5 values of the Series.

In [8]:
s.tail()

a    10
b    20
c    20
d    30
e    40
dtype: int64

##### `value_counts()`: Used to count frequency of unique values in the Series.

In [9]:
s.value_counts()

20    2
10    1
30    1
40    1
Name: count, dtype: int64

## Pandas DataFrame and Indexing Method
### Example 1:
##### `DataFrame()`: Used to create a Pandas DataFrame.

In [10]:
data={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,22,35],
    'City':['New York','Paris','London','Berlin'],
    'Salary':[70000,80000,60000,90000]
}
df=pd.DataFrame(data)
df

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30     Paris   80000
2  Charlie   22    London   60000
3    David   35    Berlin   90000

##### `loc[row_condition, column_name]`: Used for label-based row and column selection

In [11]:
subset_loc=df.loc[1:3,['Name','Salary']]
subset_loc

      Name  Salary
1      Bob   80000
2  Charlie   60000
3    David   90000

##### `iloc[row_index, column_index]`: Used for integer position-based row and column selection.

In [12]:
subset_iloc=df.iloc[0:2,1:3]
subset_iloc

   Age      City
0   25  New York
1   30     Paris

##### `df[df['column'] condition]`: Used to filter rows based on a condition.

##### Conditions:

In [13]:
high_salary=df[df['Salary']>75000]
high_salary

    Name  Age    City  Salary
1    Bob   30   Paris   80000
3  David   35  Berlin   90000

In [14]:
df.loc[df['Age']<30,'Salary']=65000
df

      Name  Age      City  Salary
0    Alice   25  New York   65000
1      Bob   30     Paris   80000
2  Charlie   22    London   65000
3    David   35    Berlin   90000

## Pandas String Cleaning in DataFrame
### Example 2:
##### `.str.strip()`: Removes leading and trailing spaces from strings.
##### `.str.lower()`: Converts all text to lowercase.
##### `.str.replace('-', ' ')`: Replaces `-` with space in string values.

In [15]:
df=pd.DataFrame({'Category':['Electronics ','furniture','Home-Appliances',' electronics','FURNITURE']})
df

          Category
0     Electronics
1        furniture
2  Home-Appliances
3      electronics
4        FURNITURE

In [16]:
df['Category_clean']=df['Category'].str.strip().str.lower()
df

          Category   Category_clean
0     Electronics       electronics
1        furniture        furniture
2  Home-Appliances  home-appliances
3      electronics      electronics
4        FURNITURE        furniture

In [17]:
df['Category_clean']=df['Category_clean'].str.replace('-',' ')
df

          Category   Category_clean
0     Electronics       electronics
1        furniture        furniture
2  Home-Appliances  home appliances
3      electronics      electronics
4        FURNITURE        furniture

## Pandas Merge & Concatenation
### Example 3:

In [18]:
customers=pd.DataFrame({'CustomerID':[1,2,3],'':['Alice','Bob','Charlie']})
orders=pd.DataFrame({'OrderID':[101,102,103,104],'CustomerID':[1,2,2,3],'Amount':[250,150,200,300]})

In [19]:
customers

   CustomerID
0           1    Alice
1           2      Bob
2           3  Charlie

In [20]:
orders

   OrderID  CustomerID  Amount
0      101           1     250
1      102           2     150
2      103           2     200
3      104           3     300

##### `pd.merge(..., how='inner')`: Used to combine two DataFrames and keep only matching rows from both tables.
##### `pd.merge(..., how='left')`: Used to keep all rows from left DataFrame and matching rows from right.
##### `pd.merge(..., how='right')`: Used to keep all rows from right DataFrame and matching rows from left.

In [21]:
df_inner=pd.merge(customers,orders,on='CustomerID',how='inner')
df_inner

   CustomerID           OrderID  Amount
0           1    Alice      101     250
1           2      Bob      102     150
2           2      Bob      103     200
3           3  Charlie      104     300

In [22]:
df_left=pd.merge(customers,orders,on='CustomerID',how='left')
df_left

   CustomerID           OrderID  Amount
0           1    Alice      101     250
1           2      Bob      102     150
2           2      Bob      103     200
3           3  Charlie      104     300

In [23]:
df_right=pd.merge(customers,orders,on='CustomerID',how='right')
df_right

   CustomerID           OrderID  Amount
0           1    Alice      101     250
1           2      Bob      102     150
2           2      Bob      103     200
3           3  Charlie      104     300

##### `pd.concat()`: Used to join DataFrames vertically or horizontally.

In [24]:
df_concat=pd.concat([customers,customers])
df_concat

   CustomerID
0           1    Alice
1           2      Bob
2           3  Charlie
0           1    Alice
1           2      Bob
2           3  Charlie