# 📊 Retail Sales Data Analysis
This project demonstrates a complete data cleaning, transformation, analysis, and export pipeline using Pandas on a retail sales dataset.

## Importing Libraries & Loading Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('retail_sales.csv')

## Basic Data Exploration

In [3]:
print("Info:\n", df.info())          # Shows column types, null values, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: float64(3), object(3)
memory usage: 85.7+ KB
Info:
 None

In [4]:
print("Shape:", df.shape)            # Rows and columns count

Shape: (1825, 6)

In [5]:
print("Data Types:\n", df.dtypes)    # Data type of each column

Data Types:
 Date         object
Category     object
Sales       float64
Quantity    float64
Profit      float64
Region       object
dtype: object

In [6]:
print("Statistical Summary:\n", df.describe())  # Numerical summary (mean, std, min, max)

Statistical Summary:
              Sales     Quantity       Profit
count  1823.000000  1820.000000  1825.000000
mean    980.482677    10.053846   248.696130
std     336.756618     5.515370   118.159627
min       0.000000     0.000000     0.000000
25%     784.071354     5.000000   156.916498
50%     997.725134    10.000000   229.344557
75%    1208.512721    15.000000   324.867847
max    1888.932537    19.000000   703.228418

## Optimized Data Loading (Memory Efficient)
- Converts Date into datetime format
- Reduces memory usage using categorical types

In [7]:
df = pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],  # Converts string dates into datetime objects
    dtype={
        "Category": "category",  # Saves memory
        "Region": "category"     # Saves memory
    }
)
df

           Date     Category        Sales  Quantity      Profit Region
0    2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1    2023-01-01     Clothing   958.520710       7.0  224.054049   East
2    2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3    2023-01-01       Sports  1230.230419       6.0  123.310460   West
4    2023-01-01         NaN?   828.585950      12.0   88.591355   East
...         ...          ...          ...       ...         ...    ...
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North
1824 2023-12-31        Books   703.973443      14.0  134.106006   East

[1825 rows x 6 columns]

## Data Type Conversion & Memory Optimization
- Converts columns into proper numeric types
- Checks memory usage

In [8]:
df.info()  # Overview before conversion

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [9]:
df['Profit'] = pd.to_numeric(df['Profit'])  # Ensures numeric format

In [10]:
df.info()  # Check after conversion

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [11]:
print(df['Region'].memory_usage(deep=True))  # Memory usage of categorical column

2395

In [12]:
df['Quantity'] = df['Quantity'].astype('Int64')  # Nullable integer type

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   Int64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: Int64(1), category(2), datetime64[ns](1), float64(2)
memory usage: 63.1 KB

## Checking and Handling Missing Values
- Identifies null values in each column
- Fills missing values using statistical methods
- Removes rows where critical data is missing

In [14]:
df.isna().sum()  #Checking

Date        0
Category    4
Sales       2
Quantity    5
Profit      0
Region      5
dtype: int64

In [15]:
df['Quantity'] = pd.to_numeric(df['Quantity'])
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mode()[0])  # Most frequent value

In [16]:
df['Sales'] = df['Sales'].fillna(df['Sales'].median())  # Median for numerical stability

In [17]:
df['Category'] = df['Category'].fillna(df['Category'].mode()[0])  # Most common category

In [18]:
df.dropna(subset=['Region'], inplace=True)  # Remove rows with missing Region

In [19]:
df.isna().sum()

Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      0
dtype: int64

## Sorting Data based on Quantity and Sales

In [20]:
df_sorted = df.sort_values(
    by=['Quantity', 'Sales'],   # Sorting keys
    ascending=[False, True]     # Quantity desc, Sales asc
)

df_sorted.head()

           Date    Category       Sales  Quantity      Profit Region
312  2023-03-04  Home Goods    0.000000        19    0.000000   West
528  2023-04-16      Sports    0.000000        19  270.577388   West
1708 2023-12-08      Sports  227.942727        19   61.534381  North
571  2023-04-25    Clothing  361.006937        19   57.285585   West
1213 2023-08-31      Sports  368.305917        19   73.419555   West

## Ranking Sales
Creates a ranking of sales within each quantity group.

In [21]:
df['Sales_rank'] = df.groupby('Quantity')['Sales'].rank(
    method='dense',     # No gaps in ranking
    ascending=False     # Highest sales get rank 1
)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1820 entries, 0 to 1824
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        1820 non-null   datetime64[ns]
 1   Category    1820 non-null   category
 2   Sales       1820 non-null   float64
 3   Quantity    1820 non-null   Int64
 4   Profit      1820 non-null   float64
 5   Region      1820 non-null   category
 6   Sales_rank  1820 non-null   float64
dtypes: Int64(1), category(2), datetime64[ns](1), float64(3)
memory usage: 91.2 KB

## Installing Export Dependency
Installs Excel writer support for exporting .xlsx files.

In [22]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: openpyxl in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from openpyxl) (2.0.0)

In [23]:
import openpyxl

## Filtering Clean Data
Removes invalid sales values (e.g., negative or zero sales).

In [25]:
clean_df = df[df["Sales"] > 0]
clean_df

,Date,Category,Sales,Quantity,Profit,Region,Sales_rank
0,2023-01-01,Electronics,1149.014246,11,383.664245,North,29.0
1,2023-01-01,Clothing,958.520710,7,224.054049,East,56.0
2,2023-01-01,Home Goods,1473.763845,2,466.593090,South,7.0
3,2023-01-01,Sports,1230.230419,6,123.310460,West,24.0
4,2023-01-01,NaN?,828.585950,12,88.591355,East,67.0
...,...,...,...,...,...,...,...
1820,2023-12-31,Electronics,1132.749004,14,353.464221,West,30.0
1821,2023-12-31,Clothing,679.261971,8,183.860200,North,88.0
1822,2023-12-31,Home Goods,1193.733728,10,359.010938,South,32.0
1823,2023-12-31,Sports,1076.118706,17,259.570916,North,38.0
1824,2023-12-31,Books,703.973443,14,134.106006,East,73.0

## Selecting Required Columns
Creates a subset for reporting or export.

In [26]:
subset = clean_df[["Date", "Category", "Sales", "Region"]]
subset

           Date     Category        Sales Region
0    2023-01-01  Electronics  1149.014246  North
1    2023-01-01     Clothing   958.520710   East
2    2023-01-01   Home Goods  1473.763845  South
3    2023-01-01       Sports  1230.230419   West
4    2023-01-01         NaN?   828.585950   East
...         ...          ...          ...    ...
1820 2023-12-31  Electronics  1132.749004   West
1821 2023-12-31     Clothing   679.261971  North
1822 2023-12-31   Home Goods  1193.733728  South
1823 2023-12-31       Sports  1076.118706  North
1824 2023-12-31        Books   703.973443   East

[1777 rows x 4 columns]

## Exporting Data
Saves processed data into Excel and JSON formats.

In [27]:
subset.to_excel("subset_sales.xlsx", sheet_name='sales')
subset.to_json("subset_sales.json", orient="records", date_format="iso")

print("Files exported successfully")

Files exported successfully

In [28]:
subset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1777 entries, 0 to 1824
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1777 non-null   datetime64[ns]
 1   Category  1777 non-null   category
 2   Sales     1777 non-null   float64
 3   Region    1777 non-null   category
dtypes: category(2), datetime64[ns](1), float64(1)
memory usage: 110.2 KB

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1820 entries, 0 to 1824
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        1820 non-null   datetime64[ns]
 1   Category    1820 non-null   category
 2   Sales       1820 non-null   float64
 3   Quantity    1820 non-null   Int64
 4   Profit      1820 non-null   float64
 5   Region      1820 non-null   category
 6   Sales_rank  1820 non-null   float64
dtypes: Int64(1), category(2), datetime64[ns](1), float64(3)
memory usage: 91.2 KB